apiVersion: v1
kind: Secret
metadata:
  name: kareelio-secret
  namespace: kareelio
type: Opaque
stringData:
  POSTGRES_USER: "kareelio"
  POSTGRES_PASSWORD: "CHANGE_ME"
  SESSION_SECRET: "CHANGE_ME"
  DEFAULT_ADMIN_EMAIL: "admin@kareelio.local"
  DEFAULT_ADMIN_PASSWORD: "CHANGE_ME"
